(mov, 3, , n)
(newarr, person, 3, t0)
(mov, t0, , people)
(param, "[SETUP] Inicializando arreglo people de tamaño 3", , )
(call, print, 1, )
(param, "Ana", , )
(call, Person.new, 1, t0)
(mov, t0, , p0)
(param, "[NEW] Creado objeto Person p0 con nombre Ana", , )
(call, print, 1, )
(param, "Ana", , )
(param, p0, , )
(call, invoke.init, 2, t0)
(param, "[INIT] p0.init completado", , )
(call, print, 1, )
(idxchk, people, 0, )
(astore, people, 0, p0)
(param, "[ARRAY] people[0] asignado a Ana", , )
(call, print, 1, )
(param, "Ben", , )
(param, 90, , )
(call, Student.new, 2, t1)
(mov, t1, , p1)
(param, "[NEW] Creado objeto Student p1 con nombre Ben y grade 90", , )
(call, print, 1, )
(param, "Ben", , )
(param, 90, , )
(param, p1, , )
(call, invoke.init, 3, t1)
(param, "[INIT] p1.init completado", , )
(call, print, 1, )
(idxchk, people, 1, )
(astore, people, 1, p1)
(param, "[ARRAY] people[1] asignado a Ben", , )
(call, print, 1, )
(param, "Cami", , )
(param, 95, , )
(call, Student.new, 2, t2)
(mov, t2, , p2)
(param, "[NEW] Creado objeto Student p2 con nombre Cami y grade 95", , )
(call, print, 1, )
(param, "Cami", , )
(param, 95, , )
(param, p2, , )
(call, invoke.init, 3, t2)
(param, "[INIT] p2.init completado", , )
(call, print, 1, )
(idxchk, people, 2, )
(astore, people, 2, p2)
(param, "[ARRAY] people[2] asignado a Cami", , )
(call, print, 1, )
(param, "[INFO] Comenzando recorrido del arreglo people (for i=0..n, incluye OOB para probar catch)", , )
(call, print, 1, )
(mov, 0, , i)
(label, L0, , )
(le, i, n, t3)
(ifz, t3, L2, )
(idxchk, people, i, )
(aload, people, i, t3)
(param, t3, , )
(call, invoke.greet, 1, t4)
(label, L1, , )
(add, i, 1, t3)
(mov, t3, , i)
(goto, L0, , )
(label, L2, , )
(param, "[TEST] Intentando división por cero para activar catch correspondiente", , )
(call, print, 1, )
(div, 10, 0, t3)
(mov, t3, , x)
(param, x, , )
(call, print, 1, )
(param, "[FINAL] PRUEBAS DE ARRAYS CHECK", , )
(call, print, 1, )
(param, "[DONE] Fin del script OK-3", , )
(call, print, 1, )